substitutions:
  name: vevor-diesel-heater
  friendly_name: Vevor Diesel Heater
  mac_address: "AA:BB:CC:DD:EE:FF"

packages:
  heater: !include heaters/vevor-8kw-ble/esphome.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:

api:

wifi:
  ssid: "SSID"
  password: "PASSWORD"
