substitutions:
  mac_address: "AA:BB:CC:DD:EE:FF"

packages:
  interface: !include common/interface.yaml
  heater: !include heaters/vevor-8kw-ble/esphome.yaml

esphome:
  name: vevor-diesel-heater
  friendly_name: Vevor Diesel Heater
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
