packages:
  base: !include heaters/vevor-8kw-ble.yaml

substitutions:
  name: vevor-diesel-heater
  friendly_name: Vevor Diesel Heater

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

logger:

api:

wifi:
  ssid: "SSID"
  password: "PASSWORD"
