substitutions:
  name: vevor-diesel-heater
  friendly_name: Vevor Diesel Heater

packages:
  heater: !include heaters/vevor-8kw-ble.yaml
  sensors: !include common/sensors.yaml
  controls: !include common/controls.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:

api:

wifi:
  ssid: "SSID"
  password: "PASSWORD"
